login:
	echo "eyJwYXlsb2FkIjoiVGZ2M2xqMFcxbDcyMU5MMldRSmtTK29vVG5VMVMzd2NRRGNnM2hsMUtJR3M3cytaeUlEUzAxM3BYOUw4Nkl2a0VmVnZnYUIzb1A3YWJ3aGhwRlhMM0JoRFgyV2dGQndtMXlsdGloMFlDcnpvQ0xWMXR2VmU1UGlzVFVLSHJYaXQveCtQMVk1RkN1V3laNmt2OGcvd1E1a1dwRHNRVDkzUitCZkRQVnVacFEwTUJ4RmVpSmNPcGxlYVVhUEFYbGhsOUYxUy9yV1dhTXk5Wk5taHdFYVBjTllBV0Y0TEFubm45NC9Tc0NmM3phYzMzRlQyQVJEd2lKbnlGby9ncG9HUGRZenA2OG45NUVNTElEbEtGNlVQNEFjYXk4bjZPbjZhU3Y3S1BuMFNRRjFhejN2a3psWU13c0k2UUJjSlFTWURDYi9oMkI3TW9xd2JFTWpBUWh2dXJHQkJpdzIxVFNqbkh3emNpaFlReVNhQlRFOHdKbUpNWE9ZaVZlY3l1Y254dmFaOTZUV0ZpN1BWSHRlK2xJR3kwMFFFTzNScU9rME9NVnlWL3MzeklDNThzbUI3dlhiSVRmSUxuZjBPMW14SXlET2dhMVl3R1JoYlhyRC84MmNVU1d4K0Jzcncyb2F4dXdIWkhqTnMxQkFER24wK21sMVVvOWhoWkFSci9vbDlja2lqRFRxQWxsaWhnM2hML016ekNmOS9MWFc1R1EzZDJhZm9vVW56elFzbmNHdmk4NlpHRm5LcGVLWHNZNWxxK0pIWjFZNjczSnBQT21BRnRTNit0VDdMNEVzTjdjMEpsVmZpekdITWVyK1pwZGc5NmM3d0xqQVFmOVNLcldaSmFheXVDNTdvaVBRcDRXRlIwbHpOZnJmMDFRRU1JdGs0UjNLMlVrRGxMd05zRUR4QmJIWlEvdTBsR0FMOCtsZnBZdVR3WG9ObVV1dGRaQStPS3BPMDU2TWZrQmluVU9RUzdoS01QZG5UWWx1aXJBTWxWM04yM2Z1UHZid0xqSi9EYWVOeEpmd3BWclJsbWxYYnRZcUVJbjNpVG5UOUpqNnhLSmsrSTFCU0lyZFQ0OVphNGx1NGdmS2d5Z0szR2cyVXIyNXIvc3ovRnN2MGNDNCtYZWxXYnhJZTNVNDFuNDV1ZHM1Y0VoOFdqZ3VxTW9qeXduSWRra3dNeVdIUzFYUDhYZVNZR2tlOFpJNEFjekRpeVpuRTJMaVNrWm0zUlVQczdmcDRLeVRqQmpKMTI4TEdMQk9wYnkrYzR0MHZKZlNJbWZCOFE1VFpreFVwdk4rN0J1eGhWL3QxLzJaMjVlRVpZREpLa3R6T2pNK2ZiRlNsd1pDdVlCdzR2aG9aYVBZVFpUVjlsMzhGeGNPanRmUHA3Y00rdWR3ajRVMGNpRlBWckVFOXRmOGIyRHh4TVhTRUprbDkzU0M2K0pUS1paVndteG5SeS9nYUR6U0FwZ2wwMFFvNW1BOHJ1RHU4SEYwM3lFTDBwOGxWblFWYkxia3lCcmV0dVVHVlB2b2ZaQT09IiwiZGF0YWtleSI6IkFRSUJBSGlYdldPamxweXJyK0R2SFp3SW11UkgvNWNOL2g5d1RibHY2K3p4MUt3aVhRSDZOOElrSlpJKzY4SlJUWlV0M3I4Z0FBQUFmakI4QmdrcWhraUc5dzBCQndhZ2J6QnRBZ0VBTUdnR0NTcUdTSWIzRFFFSEFUQWVCZ2xnaGtnQlpRTUVBUzR3RVFRTVA4OFdpYU5QRGNseGxvcjJBZ0VRZ0R1c2gxS2tHb0JETkYvRkZjSVBTUVFpL0dLZGh3UGlZV3gvY2xxS2U5THAxMHZQMlppTEZLemhPWEsxNVhlTWlGY2pkVEdFUjRLWWtZRlFBdz09IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNjEzNDQwNzEyfQ==" | docker login --username AWS --password-stdin public.ecr.aws/x6l5c3l5

ping:
	docker build -t ping:1 -f ping/Dockerfile .
	docker tag ping:1 public.ecr.aws/x6l5c3l5/tikal:ping
	docker push public.ecr.aws/x6l5c3l5/tikal:ping

pong:
	docker build -t pong:1 -f pong/Dockerfile .
	docker tag pong:1 public.ecr.aws/x6l5c3l5/tikal:pong
	docker push public.ecr.aws/x6l5c3l5/tikal:pong

apply:
	kubectl apply -f manifests

apply-extra:
	kubectl apply -f manifests/pong-service.yaml
	kubectl apply -f extra-manifests/configmap.yaml
	kubectl apply -f extra-manifests/ping-pod.yaml
	kubectl apply -f extra-manifests/pong-pod.yaml

cleanup:
	kubectl delete pods --all
	kubectl delete service pong --ignore-not-found
	kubectl delete configmaps --all

redeploy:
	$(MAKE) cleanup
	$(MAKE) apply

redeploy-extra:
	$(MAKE) cleanup
	$(MAKE) apply-extra
