apiVersion: v1
kind: Pod
metadata:
  name: ping
spec:
  containers:
  - name: ping
    image: public.ecr.aws/x6l5c3l5/tikal:ping
    command: ["./ping"]
    env:
    - name: HOSTNAME
      value: pong
    - name: PORT
      value: "9001"
